### ISSUE TITLE
How does it work exactly?

### ISSUE THREAD

**Issue by ghost** [MrGreenTea/GodotTiledImporter#4] opened 2015-05-10 12:27 UTC
I saved a map from Tiled called map.json and when I click the "Import Tiled Map" from the top, I don't know what option to click. Choose File or Import Map?

What do they do?

**Comment by MrGreenTea** [comment] 2015-05-10 16:32
Choose File lets you choose the file to import and clicking Import Map imports the file as a tilemap-node into the editor.

**Comment by ghost** [comment] 2015-05-10 16:38
Ok, I chose the file and then I clicked on import map but nothing happens

**Comment by MrGreenTea** [comment] 2015-05-10 16:41
Most probably you are using an old version of Tiled. Get the newest one from their website and it should work. If it still doesn't, I'll need more info about the environment you are using.

**Comment by ghost** [comment] 2015-05-10 16:51
I am using 0.11.0 Tiled, which is the latest version. I am on Mac OS Yosemite

**Comment by MrGreenTea** [comment] 2015-05-10 16:58
Could you please send me the file you are trying to import? I'll also need the tileset image.

**Comment by ghost** [comment] 2015-05-10 17:15
The tile image:
![basictiles_2](https://cloud.githubusercontent.com/assets/12121132/7555334/684c5280-f740-11e4-974f-d7e7bf5573ac.png)

The room1.json code:

{ "height":20,
 "layers":[
        {
         "data":[65, 65, 12, 66, 65, 65, 12, 12, 12, 12, 66, 66, 2, 12, 12, 12, 12, 65, 2, 65, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 66, 66, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 2, 12, 12, 66, 65, 12, 2, 12, 65, 66, 65, 12, 66, 12, 12, 66, 65, 12, 66, 65, 12, 12, 12, 12, 12, 12, 12, 12, 12, 65, 3, 3, 12, 12, 3, 3, 3, 66, 12, 12, 12, 12, 12, 12, 12, 12, 12, 65, 66, 12, 12, 12, 12, 65, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 66, 12, 12, 12, 12, 65, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 66, 66, 65, 12, 12, 12, 66, 65, 12, 65, 65, 65, 12, 12, 65, 12, 65, 65, 65, 65, 65, 65, 12, 12, 65, 65, 65, 65, 65, 65, 65, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 66, 65, 66, 65, 12, 12, 12, 12, 12, 12, 65, 65, 65, 12, 12, 20, 12, 12, 12, 12, 12, 65, 66, 12, 12, 12, 12, 12, 12, 12, 65, 65, 65, 12, 12, 12, 66, 65, 66, 12, 12, 65, 20, 65, 12, 12, 12, 12, 12, 12, 12, 12, 65, 12, 12, 65, 12, 12, 65, 12, 12, 12, 12, 12, 12, 12, 12, 12, 65, 12, 12, 12, 12, 12, 12, 12, 65, 65, 12, 12, 65, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 65, 65, 65, 65, 12, 12, 12, 65, 12, 12, 12, 65, 12, 12, 66, 12, 12, 66, 65, 66, 65, 12, 12, 65, 12, 12, 12, 12, 12, 65, 65, 65, 65, 12, 12, 12, 12, 12, 12, 12, 65, 66, 12, 65, 12, 12, 12, 65, 65, 12, 66, 12, 12, 12, 12, 12, 65, 65, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 65, 65, 65, 12, 65, 12, 12, 65, 65, 12, 12, 12, 12, 12, 12, 12, 12, 65, 65, 12, 12, 12, 12, 12, 65, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 66, 66, 66, 12, 65, 66, 66, 65, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 65, 65, 12, 65, 65, 12, 12, 65, 65, 65, 65, 12, 12, 12, 66, 12, 12, 12, 12, 12, 12, 12, 12, 12, 65, 65, 12, 12, 65, 65, 65, 12, 12, 66, 65, 12, 65, 65, 65, 65, 66, 65, 12, 12, 12, 65, 65, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 66, 65, 66, 12, 12, 12, 12, 12, 12, 12, 12, 65, 12, 12, 66, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 12, 12, 12, 65, 66, 12, 12, 12, 66, 12, 12, 65, 66, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 12, 12, 12, 12, 12, 12, 12, 66, 66, 12, 65, 65, 12, 65, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 66, 12, 12, 66, 65, 65, 65, 66, 12, 65, 65, 65, 12, 12, 12, 12, 65, 65, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 66, 66, 65, 66],
         "height":20,
         "name":"grass",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":30,
         "x":0,
         "y":0
        }, 
        {
         "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 9, 9, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 9, 9, 9, 9, 9, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 11, 11, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 11, 11, 11, 11, 11, 11, 11, 0, 0, 0, 0, 0, 0, 25, 26, 26, 26, 26, 26, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 0, 0, 0, 0, 0, 0, 33, 0, 42, 42, 42, 42, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 0, 0, 0, 0, 0, 0, 33, 35, 14, 14, 14, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 11, 11, 11, 11, 11, 11, 11, 0, 0, 0, 0, 0, 0, 33, 35, 14, 14, 25, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 11, 11, 11, 11, 11, 11, 11, 0, 0, 0, 0, 0, 0, 16, 16, 14, 14, 16, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 11, 0, 0, 0, 0, 0, 0, 0, 0, 59, 0, 35, 14, 14, 33, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 14, 14, 33, 0, 0, 0, 0, 0, 42, 42, 42, 42, 42, 42, 42, 42, 42, 11, 11, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 43, 14, 14, 33, 0, 0, 0, 0, 35, 14, 14, 14, 14, 14, 14, 14, 14, 14, 89, 89, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 33, 0, 0, 0, 0, 35, 14, 14, 14, 14, 14, 14, 14, 14, 14, 89, 89, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 33, 0, 0, 0, 0, 35, 14, 14, 25, 26, 26, 26, 26, 26, 26, 11, 11, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 0, 0, 0, 0, 0, 35, 14, 14, 33, 0, 0, 0, 0, 0, 0, 11, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59, 0, 0, 0, 0, 0, 0, 35, 14, 14, 33, 0, 0, 0, 0, 0, 0, 11, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 14, 14, 33, 0, 0, 0, 0, 0, 0, 11, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 14, 14, 33, 0, 0, 0, 0, 0, 0, 11, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         "height":20,
         "name":"sand and water",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":30,
         "x":0,
         "y":0
        }],
 "nextobjectid":1,
 "orientation":"orthogonal",
 "properties":
    {

```
},
```

 "renderorder":"right-down",
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "image":"LD\/levels\/basictiles_2.png",
         "imageheight":480,
         "imagewidth":256,
         "margin":0,
         "name":"basictiles_2",
         "properties":
            {

```
        },
     "spacing":0,
     "tileheight":32,
     "tilewidth":32,
     "transparentcolor":"#ff00ff"
    }, 
    {
     "firstgid":121,
     "image":"LD\/levels\/things_0.png",
     "imageheight":256,
     "imagewidth":384,
     "margin":0,
     "name":"things_0",
     "properties":
        {

        },
     "spacing":0,
     "tileheight":32,
     "tilewidth":32,
     "transparentcolor":"#ff00ff"
    }],
```

 "tilewidth":32,
 "version":1,
 "width":30
}

**Comment by MrGreenTea** [comment] 2015-05-10 17:15
It doesn't work like this. Please send me the file, not only the content of the file.

**Comment by ghost** [comment] 2015-05-10 17:17
Here is the file again: https://dl.dropboxusercontent.com/u/61305568/room1.json

**Comment by MrGreenTea** [comment] 2015-05-10 17:24
It works perfectly fine for me. You forgot the  second tileset, but I could just delete it from the .json file. 
A few things you should try:
1. Try to put all the files in the project directory. Make sure all paths are valid. You can do this by opening the file in Tiled and if it opens it without complaining, everything should be fine.
2. Make sure you have a root node

If it still doesn't work, can you take a look at the console? Maybe it tells you something. Else I am all out of ideas and it's going to be quite the effort to find the cause of this.

**Comment by ghost** [comment] 2015-05-11 06:49
I have a Node2D as root node, I made a new Tiled map saved as .json and have the spritesheet.png in the same directory. 
My exact steps: Click on IMPORT TILED MAP at the top right. Click CHOOSE FILE and choose my json file (it does let me do this). Click IMPORT MAP, but nothing happens. Does it create its own TileMap, or do I have to make mine?

Also, how do I take a look at the console?

**Comment by MrGreenTea** [comment] 2015-05-11 09:07
Could you please try to put these files in the folder of your project and try to import the map?
http://wikisend.com/download/599310/room1.zip 
I don't know for OSX, but you could try to run the godot binary from a console/terminal. At least that's what I am doing on linux. Else you have to google it.
BTW, did you create the spritesheet image? It looks really nice!

**Comment by ghost** [comment] 2015-05-11 16:27
Yes, now it does import the tileset however, is it supposed to import the map, or just the tileset?
PS: I made the terrain tiles, the objects where made by a friend

**Comment by ghost** [comment] 2015-05-11 16:29
BTW, what was the problem?

**Comment by tbruyelle** [comment] 2015-05-11 21:07
Thanks to your zip file @MrGreenTea, I managed to make it work. But I had to reboot Godot or else nothing happen. Maybe the previous attempts broke the plugin and so it needs a fresh start.

Then I managed to import my own work. Thanks!

**Comment by MrGreenTea** [comment] 2015-05-11 21:53
It will import the map and all the saved tilesets if possible. It most probably fails completely if something goes wrong. I'll try to work on that and add more help from the program itself. I can imagine that the problem were the file locations. I recommend editing the file directly in the project directory, so that Tiled saves all path right. 
@tbruyelle, I'm glad you got it working. Feel free to open new issues or ask me questions :) I'm also very open to suggestions for improvement.

**Comment by MrGreenTea** [comment] 2015-05-11 21:53
@AxelAlco, can I close this issue now?

**Comment by T12E** [comment] 2015-05-12 06:47
> It most probably fails completely if something goes wrong.

Yes you need to improve error handling and feedback.

> I can imagine that the problem were the file locations. I recommend editing the file directly in the project directory, so that Tiled saves all path right.

Yes that what I did to make it work.

> Feel free to open new issues or ask me questions :)

Where should I ask questions ?

**Comment by MrGreenTea** [comment] 2015-05-12 08:13
Simple questions are best asked in the forum thread, with a pm or if I am there in the IRC. The Github issue page is for bugs and enhancement of the Plugin, so I would like to keep it that way. But maybe I will leave this issue open for people who need help and want to get it here on Github.

**Comment by tbruyelle** [comment] 2015-05-12 21:07
> Simple questions are best asked in the forum thread

Then you should add the forum link in the README, and maybe put also the various informations you added in the original post.

**Comment by MrGreenTea** [comment] 2015-05-13 07:53
Sure, you can do that too :)

**Comment by tbruyelle** [comment] 2015-05-13 08:50
Yes I know, maybe later don't have the time actually.

**Comment by ghost** [comment] 2015-05-13 17:46
One last question: Does collision data from Tiled also import into Godot?

**Comment by MrGreenTea** [comment] 2015-05-13 17:50
Yes, it should import most of the shapes from tiled. I didn't code it, but here is what the guy who did said:

> The shapes that work are Rectangle, Circle, Ellipse, Convex Polygon, and Concave Polygon. Rectangle, circle, and ellipse all work as you would expect. However, there are two things to note about polygon colliders:
> 
> 1: For both concave and convex polygon colliders, you have to draw your polygon points in CLOCKWISE order in Tiled. Otherwise, the colliders won't work well in Godot.
> 2: In the Tiled collision editor (View -> Tile Collision Editor), use "Polygon" for convex polygon colliders and "Polyline" for concave polygon colliders. This was the only way I could think to differentiate convex from concave in the importer.

If you can, please use the forum for help though, as this page is more for bugs and feature ideas.

**Closed as completed** 2015-05-13 18:00 UTC
Labels: help wanted
